version = 1

test_patterns = [
    "tests/**"
]

exclude_patterns = ["tests/**"]

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "Dockerfile"
  ]

  trusted_registries = [
    "registry.hub.docker.com"
  ]
